---

# common
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: install git
    action: apt name=git state=installed update_cache=yes

# web
- hosts: web
  sudo: yes
  vars:
    # https://github.com/jweissig/episode-47/releases
    app_version: release-0.01
  serial: 1

  pre_tasks:

  - name: disable server in haproxy
    shell: echo "disable server episode46/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.lb

  tasks:

  - name: install nginx
    action: apt name=nginx state=installed

  - name: write our nginx.conf
    action: template src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: write our /etc/nginx/sites-available/default
    action: template src=templates/default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: clean existing website content
    #shell: rm -f /usr/share/nginx/html/*
    file: path=/usr/share/nginx/html/ state=absent

  - name: deploy website content
    git: repo=https://github.com/jweissig/episode-47.git
         dest=/usr/share/nginx/html/
         version={{ app_version }}

  handlers:

  - name: restart nginx
    action: service name=nginx state=restarted

  post_tasks:

  - name: enable server in haproxy
    shell: echo "enable server episode46/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.lb

# lb
- hosts: lb
  sudo: yes  

  tasks:

  - name: Download and install haproxy and socat
    apt: pkg={{ item }} state=latest
    with_items:
    - haproxy
    - socat

  - name: Enable HAProxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy 

  - name: Configure the haproxy cnf file with hosts
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted
